# You can use the following limits on your named parameters.
# *                    // Match all request URIs
# [i]                  // Match an integer
# [i:id]               // Match an integer as 'id'
# [a:action]           // Match alphanumeric characters as 'action'
# [h:key]              // Match hexadecimal characters as 'key'
# [:action]            // Match anything up to the next / or end of the URI as 'action'
# [create|edit:action] // Match either 'create' or 'edit' as 'action'
# [*]                  // Catch all (lazy, stops at the next trailing slash)
# [*:trailing]         // Catch all as 'trailing' (lazy)
# [**:trailing]        // Catch all (possessive - will match the rest of the URI)
# .[:format]?          // Match an optional parameter 'format' - a / or . before the block is also optional
#
# Methods: GET|POST|PATCH|PUT|DELETE
# - ['method', 'route', 'controller#action', 'name']
#
# Example:
# 	- ['GET|POST', /users/[i:id]/, 'user#show', 'user_show']
# Example Match:
# 	/users/53/
# Variables:
# 	$id: 53
- ['GET', '/', 'static#index', 'home']